name: CI

on:
  pull_request:

jobs:
  core-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v4
        name: Set up Python 3.9
        with:
          python-version: 3.9
      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          make install
      - name: Test
        run: |
          make test

  success-all-test:
    needs: core-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "All Done"
